name: docs

on:
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * *'
  push:
    branches:
      - master
    paths:
      - '**.rst'
      - '**/docs.yml'


env:
  DOCS_REPO: SoCXin/web
  DOCS_DIR: docs
  LATEST_DOCS_DIR: latest

jobs:
  build:
    if: github.repository_owner == 'SoCXin'
    name: vendor
    strategy:
      matrix:
        REPO:
          - wch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          token: ${{ secrets.SOC_XIN_TOCKEN }}
          fetch-depth: 1

      - name: Checkout Docs
        uses: actions/checkout@v3
        with:
          repository: SoCXin/${{ matrix.REPO}}
          token: ${{ secrets.SOC_XIN_TOCKEN }}
          ref: main
          fetch-depth: 1
          path: www

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: www
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build docs
        working-directory: www
        run: |
          tox -e docs

      - name: Preserve Docs
        run: |
          tar -czvf ${{ matrix.REPO}}.tar.gz -C www/_build html rtdpage

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.REPO}}
          path: ${{ matrix.REPO}}.tar.gz

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.REPO}}

      - name: Unpack artifact
        run: |
          mkdir ./${{ env.LATEST_DOCS_DIR }}
          tar -xzf ./${{ matrix.REPO}}.tar.gz -C ./${{ env.LATEST_DOCS_DIR }}

      - name: Checkout latest Docs
        continue-on-error: true
        uses: actions/checkout@v3
        with:
          repository: ${{ env.DOCS_REPO }}
          path: ${{ env.DOCS_DIR }}
          ref: gh-pages

      - name: Synchronize Docs
        run: |
          rm -rf ${{ env.DOCS_DIR }}/.git
          rm -rf ${{ env.DOCS_DIR }}/${{ matrix.REPO}}/
          mkdir -p ${{ env.DOCS_DIR }}/${{ matrix.REPO}}/
          cp -rf ${{ env.LATEST_DOCS_DIR }}/html/* ${{ env.DOCS_DIR }}/${{ matrix.REPO}}/

      - name: Validate Docs
        run: |
          if [ -z "$(ls -A ${{ env.DOCS_DIR }})" ]; then
            echo "Docs folder is empty. Aborting!"
            exit 1
          fi

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.SOC_XIN_TOCKEN }}
          external_repository: ${{ env.DOCS_REPO }}
          publish_dir: ./${{ env.DOCS_DIR }}
          commit_message: Sync Docs
